version: '3.3'

services:
  web:
    container_name: apt-website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/apt-website/ssl:/etc/nginx/ssl:ro
      - /home/apt-website/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped 